### ISSUE TITLE
root_folder does nothing

### ISSUE THREAD

**Issue by designermonkey** [MeilleursAgents/terraform-provider-ansiblevault#118]
What is the need for the required `root_folder` parameter when it is not used anywhere?

**Comment by bdronneau** [comment]
Hi @designermonkey ,

It's use in https://github.com/MeilleursAgents/terraform-provider-ansiblevault/blob/578d4ecd1ed2c39bdc4b82ed805d293dbc08430a/pkg/provider/provider.go#L47

**Comment by bdronneau** [comment]
Do you have an use where this parameter is ignored ?

**Comment by designermonkey** [comment]
I had searched for it using github and it didn't show that instance of the word! Sorry for that!
