### ISSUE TITLE
add darwin-arm64 to builds

### ISSUE THREAD

**Issue by fwurzel** [MeilleursAgents/terraform-provider-ansiblevault#119]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to have a published darwin-arm64 version of the software. Building it locally works but installing it with automated scripts that look online doesn't.

**Describe alternatives you've considered**
Building myself.

**Comment by Tyron2k** [comment]
Created a pull request from my fork. 
Had the same problem. 
Feel free to use https://registry.terraform.io/providers/Tyron2k/ansiblevault/latest until it´s merged.

**Comment by bdronneau** [comment]
Hello,

Available in https://github.com/MeilleursAgents/terraform-provider-ansiblevault/releases/tag/v2.3.0
