### ISSUE TITLE
publish version

### ISSUE THREAD

**Issue by bdronneau** [MeilleursAgents/terraform-provider-ansiblevault#130]
**Describe the bug**
Versions 2.3.0 is not visible on terraform registry 

**To Reproduce**
1. Go to https://registry.terraform.io/providers/MeilleursAgents/ansiblevault/latest
1. Latest version is not 2.3.0

**Expected behavior**
Get latest version

**Environment (please complete the following information):**
 - N/A

**Additional context**

**Comment by bdronneau** [comment]
Hello,

I missing rights on registry.terraform.io cc @wowane & @airbe

**Comment by bdronneau** [comment]
Up @wowane

**Comment by rostik5530** [comment]
please make the release as soon as possible

**Comment by pdecat** [comment]
Hi @bdronneau,

you should probably ask [terraform registry support](https://developer.hashicorp.com/terraform/registry/providers/publishing#support) why the new version is not automatically discovered by the terraform registry.

**Comment by bdronneau** [comment]
Yes need to talk with guys in order to add my public key

**Comment by bdronneau** [comment]
All good https://registry.terraform.io/providers/MeilleursAgents/ansiblevault/latest
