### ISSUE TITLE
Build darwin_arm64 version

### ISSUE THREAD

**Issue by jmapro** [MeilleursAgents/terraform-provider-ansiblevault#133]
Hi !

I'm working on a Macbook M2 and need a darwin_arm64 version of your amazing provider. Is it possible to have a version for darwin_arm64 ?

Thanks

**Comment by grzechukol** [comment]
I didn't tested it myself but I can see release with `darwin_arm64` arch, ref. https://github.com/MeilleursAgents/terraform-provider-ansiblevault/releases/tag/v2.3.0. However it's not published in Terraform registry, ref. https://registry.terraform.io/providers/MeilleursAgents/ansiblevault/latest
<img width="701" alt="image" src="https://user-images.githubusercontent.com/4355958/224366136-678f4b26-56a1-4ac3-a7b8-71cd54c23924.png">

**Comment by jmapro** [comment]
Good catch, it's related to https://github.com/MeilleursAgents/terraform-provider-ansiblevault/issues/130
