### ISSUE TITLE
Add the possibility to read a variable encrypted with vault

### ISSUE THREAD

**Issue by gvcgael** [MeilleursAgents/terraform-provider-ansiblevault#39]
**Is your feature request related to a problem? Please describe.**

It would be really useful to store ansible-vault encrypted string directly in tfvars files.
This way terraform could pass these encrypted strings to ansible provisionning without storing it in clear, but also read these values for himself.

**Describe the solution you'd like**

For example : 

```hcl
data "ansiblevault_string" "api_key" {
  encrypted = "!vault |
          $ANSIBLE_VAULT;1.1;AES256
          66386439653236336462626566653063336164663966303231363934653561363964363833313662
          6431626536303530376336343832656537303632313433360a626438346336353331386135323734
          62656361653630373231613662633962316233633936396165386439616533353965373339616234
          3430613539666330390a313736323265656432366236633330313963326365653937323833366536
          34623731376664623134383463316265643436343438623266623965636363326136"
}

${data.ansiblevault_string.api_key.value} will contain value encrypted in the string
```

**Comment by bdronneau** [comment]
Hi @gvcgael ,

We'll take a look on this feature.

**Comment by bdronneau** [comment]
Hey,

Pull request is open #41, I'll generate a 1.3 after merge is done

**Comment by bdronneau** [comment]
Available in https://github.com/MeilleursAgents/terraform-provider-ansiblevault/releases/tag/v1.3.0

**Comment by gvcgael** [comment]
Yeay ! 

Small question : why is it required to pass a `key` parameter to the data block ?

**Comment by bdronneau** [comment]
Hi,
`data "ansiblevault_string"` is a selector of yaml key in vault send throught `encrypted`.
If you want to make this reusable, use variable

```hcl
variable "vault" {
  type = string
  default = <<EOF
$ANSIBLE_VAULT;1.1;AES256
65346463633165666232636636346631626565616132653339343961656336643930323937313231
3436383237633937636435636366386563313233366630380a316535376661653933373836633130
30336130396635363830373135643261346437366235303463643538336561356534666161353233
6133626433333965320a323966396162656332386265306539666436643033653466636335363363
35656432663266353133623834653735656534346639623233623531363332373461
EOF
}

data "ansiblevault_string" "string" {
  encrypted = var.vault
  key = "API_KEY"
}
```

**Comment by gvcgael** [comment]
But why do you add a yaml key in the string ? 

https://docs.ansible.com/ansible/latest/user_guide/playbooks_vault.html#single-encrypted-variable

```
variable "vault" {
  type = string
  default = <<EOF
$ANSIBLE_VAULT;1.1;AES256
65346463633165666232636636346631626565616132653339343961656336643930323937313231
3436383237633937636435636366386563313233366630380a316535376661653933373836633130
30336130396635363830373135643261346437366235303463643538336561356534666161353233
6133626433333965320a323966396162656332386265306539666436643033653466636335363363
35656432663266353133623834653735656534346639623233623531363332373461
EOF
}

data "ansiblevault_string" "string" {
  encrypted = var.vault
}```

Should be enough don't you think ?

**Comment by bdronneau** [comment]
In our usage we do not use single encrypted variable. Our vaults are yaml format.
I'll check if the is a way to add this feature.

**Comment by gvcgael** [comment]
Well this data should be called "ansiblevault_yaml" probably then !

**Comment by trygvis** [comment]
Being able to slurp an entire vault file into a variable would be great, I keep SSH key files in vault files.

**Comment by ViBiOh** [comment]
@gvcgael By adding a true yaml parser, we have turn `key` param to optional. If key not provided, the decrypted data are return as it. Check out our example https://github.com/MeilleursAgents/terraform-provider-ansiblevault/pull/52/files#diff-e064ebb7d8fee15a0138bce21b1a19c5R23 and tell us if it meets your need

**Comment by gvcgael** [comment]
This seems perfect ! Thank you very much for your work !

**Comment by ViBiOh** [comment]
We'll merge it today and bump to v2 (we have removed keySeparator parameter)
