### ISSUE TITLE
Default root_folder to .

### ISSUE THREAD

**Issue by aeons** [MeilleursAgents/terraform-provider-ansiblevault#48]
We are not using ansible, except for ansible-vault. This means that in all cases we are using this provider, we are passing `root_folder = "."`. I wonder if that would make sense as a default?

**Comment by bdronneau** [comment]
Hi @aeons,

Indeed, we do not enforce default value of envars `ANSIBLE_ROOT_FOLDER` and we have no plan to implement this behavior because it's an edge case from our point of view.

Best

**Comment by aeons** [comment]
Sure, it's just a suggestion.

**Comment by bdronneau** [comment]
If it's okay for you, you can close this issue.
