### ISSUE TITLE
Support multiline YAML values

### ISSUE THREAD

**Issue by trygvis** [MeilleursAgents/terraform-provider-ansiblevault#50]
**Describe the bug**
If the encrypted file looks like this:

```
foo: |
  bar
  baz
```

The literal value in the Terraform script becomes ` |`.

**Comment by ViBiOh** [comment]
Hi @trygvis ,

Thank you for your feedback, actually we do not "parse" the yaml but read it line by line (expecting one entry per line). In case of multiline string, it breaks. We'll look to fix it soon.

**Comment by ViBiOh** [comment]
Resolved by #52, we added a test for it.

We'll release a v2 soon. We add fix for #47 and we're ready to release it
